// This file was auto-generated by Fern from our API Definition.

package counterparts

import (
	monitegoclient "github.com/team-monite/monite-go-client"
)

type CounterpartVatId struct {
	Country *monitegoclient.AllowedCountries `json:"country,omitempty" url:"-"`
	Type    *monitegoclient.VatIdTypeEnum    `json:"type,omitempty" url:"-"`
	Value   string                           `json:"value" url:"-"`
}

type CounterpartUpdateVatId struct {
	Country *monitegoclient.AllowedCountries `json:"country,omitempty" url:"-"`
	Type    *monitegoclient.VatIdTypeEnum    `json:"type,omitempty" url:"-"`
	Value   *string                          `json:"value,omitempty" url:"-"`
}
