// This file was auto-generated by Fern from our API Definition.

package accounting

import (
	monitegoclient "github.com/team-monite/monite-go-client"
)

type AccountingConnectionRequest struct {
	Platform *monitegoclient.Platform `json:"platform,omitempty" url:"-"`
}
